### ISSUE TITLE
How I can run this code in Google Colab? 

### ISSUE THREAD

**Issue by aram-mostowfi** [PacktPublishing/TensorFlow-1x-Deep-Learning-Cookbook#1]
When I run this code, I face many lines of errors ! 
and I am new to it. No idea how to handle it !! 
please help me

**Comment by sonam-packt** [comment]
@aramdsc  Please check if you have valid packages/data files.

**Comment by amita-kapoor** [comment]
The Google colab now comes with TensorFlow 2.x and Python 3. The code in this book was written for TensorFlow 1.x, so the first step would be to downgrade TensorFlow. The better way would be to disable TF2 behavior using `tf.compat.v1.disable_v2_behavior()`

And best would be to refer to the codes of the second edition of the book- which contains code compatible with TF2.
